import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Stockify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased min-h-screen flex flex-col`}>
        <main className="flex-grow flex flex-col min-h-0 ">{children}</main>
      </body>
    </html>
  );
}
