export const predefinedCategories = {
    'Alimentos y bebidas': [
        'Frutas',
        'Verduras',
        'Carnes',
        'Lácteos',
        'Bebidas',
        'Snacks',
        'Especias',
        'Panadería',
        'Cereales',
        'Congelados',
    ],
    'Bienes e insumos': [
        'Materiales de construcción',
        'Productos químicos',
        'Herramientas',
        'Mobiliario',
        'Suministros de oficina',
        'Papelería',
        'Accesorios eléctricos',
        'Ropa de trabajo',
        'Repuestos automotrices',
        'Equipos de protección',
    ],
    'Tecnología': [
        'Computadoras',
        'Tabletas',
        'Smartphones',
        'Accesorios de PC',
        'Software',
        'Hardware',
        'Redes',
        'Impresoras',
        'Electrónica de consumo',
        'Gadgets',
    ],
    'Salud': [
        'Medicamentos',
        'Equipo médico',
        'Vitaminas y suplementos',
        'Cuidado personal',
        'Productos naturales',
        'Servicios médicos',
        'Prótesis',
        'Instrumental quirúrgico',
        'Ropa médica',
        'Productos de higiene',
    ],
};
